language: go
  only:
  - master

sudo: required
language: go
env:
  - GO111MODULE=on
go:
  - 1.14.x
services:
  - docker

script:
  - go get -u
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server ./cmd/basic/main.go
  - docker build -t ilanpillemer/corona .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ilanpillemer/corona