branches:
  only:
  - master

sudo: required
language: go
env:
  - GO111MODULE=on
  - COMMIT=${TRAVIS_COMMIT::8}

go:
  - 1.14.x
services:
  - docker

script:
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server ./cmd/server/main.go
  - docker build -t ilanpillemer/corona:"$COMMIT" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ilanpillemer/corona:"$COMMIT"